/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2024-02-25 17:18:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.fitto.gui.utils.SessionManagementUtils;
import com.fitto.gui.utils.AESEncryption;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.fitto.gui.utils.SessionManagementUtils");
    _jspx_imports_classes.add("com.fitto.gui.utils.AESEncryption");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 HttpSession httpSession =request.getSession(false);
    System.out.println(" From JSP"+httpSession.isNew());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

String restApiUrl =  System.getenv("PINDOMAIN");
String apiKey = System.getenv("API_KEY");

String passwordReset = request.getParameter("passwordReset");
if(passwordReset != null) {
	AESEncryption encryption = new AESEncryption();
	String decryptUserName = encryption.decrypt(passwordReset);
	SessionManagementUtils sessionManagementUtils = new SessionManagementUtils();
	sessionManagementUtils.invalidateAllSessionsOfUser(decryptUserName);
}


      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Login Page</title>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"shortcut icon\" type=\"image/png\" href=\"../images/favicon.ico\" />\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/6.1.95/css/materialdesignicons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  \r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/login.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <main class=\"d-flex align-items-center min-vh-100 py-3 py-md-0\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"card login-card\">\r\n");
      out.write("        <div class=\"row no-gutters\">\r\n");
      out.write("          <div class=\"col-md-5\">\r\n");
      out.write("            <img src=\"../images/login.jpg\" alt=\"login\" class=\"login-card-img\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-7\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <div class=\"brand-wrapper\">\r\n");
      out.write("                <img src=\"../images/app_logo.png\" alt=\"logo\" class=\"logo\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"loginDivId\">\r\n");
      out.write("              <p class=\"login-card-description\">Sign into your Pin System account</p>\r\n");
      out.write("              <div class=\"error-msg-div\"><span id=\"loginErrorMsgTextId\"></span></div>\r\n");
      out.write("              <form method=\"POST\" action='");
      out.print( response.encodeURL("j_security_check") );
      out.write("'  class=\"login-form\">\r\n");
      out.write("              \t  <input type=\"hidden\" id=\"restApiUrlId\" value=\"");
      out.print(restApiUrl);
      out.write("\"/>\r\n");
      out.write("              \t   <input type=\"hidden\" id=\"apiKeySession\"  value=\"");
      out.print(apiKey);
      out.write("\"/>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"username\" class=\"sr-only\">User Name</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"j_username\" maxlength=\"45\" placeholder=\"User Name\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-group mb-4\">\r\n");
      out.write("                    <label for=\"password\" class=\"sr-only\">Password</label>\r\n");
      out.write("                    <input type=\"password\" placeholder=\"***********\" name=\"j_password\" id=\"loginPasswordId\" class=\"form-control\" style=\"width: 85%;float: left;\"/>\r\n");
      out.write("                    <div class=\"toggle-pwd-div\">\r\n");
      out.write("\t\t\t\t\t <a class=\"toggle-pwd-btn\" onclick=\"togglePassword()\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-eye-open\" id=\"togglePassword\"></i>\r\n");
      out.write("\t\t\t\t\t </a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <input name=\"login\" id=\"login\" class=\"btn btn-block login-btn mb-4\" type=\"submit\" value=\"Login\">\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"#\" class=\"forgot-password-link\" onclick=\"showForgetPassword()\">Forgot password?</a>                \r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               <div id=\"forgotPasswordDivId\" style=\"display: none;\">\r\n");
      out.write("               \t<p class=\"forgot-password-description\">Please enter your Email Id registered with us, to send you a link to reset the password.</p>\r\n");
      out.write("               \t  <div class=\"form-group row\">  \r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"error-messages\" id=\"resetPasswordErrorDiv\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("               \t  <form method=\"POST\" class=\"login-form\" id=\"forgetPassword\">\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"emailId\" class=\"sr-only\">Email Id</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"emailId\" id=\"forgetPasswordEmail\" maxlength=\"45\" placeholder=\"Email Id\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <input name=\"forgotPassword\" id=\"forgotPassword\" class=\"btn btn-block login-btn mb-4\" type=\"submit\" value=\"Reset Password\">\r\n");
      out.write("                </form>\r\n");
      out.write("                <a href=\"#\" class=\"forgot-password-link\" onclick=\"redirectToLogin()\">Back to Login</a>  \r\n");
      out.write("               </div>\r\n");
      out.write("               <!--  <a href=\"#\" class=\"forgot-password-link\">Forgot password?</a>\r\n");
      out.write("                <p class=\"login-card-footer-text\">Don't have an account? <a href=\"#\" class=\"text-reset\">Register here</a></p>\r\n");
      out.write("                <nav class=\"login-card-footer-nav\">\r\n");
      out.write("                  <a href=\"#\">Terms of use.</a>\r\n");
      out.write("                  <a href=\"#\">Privacy policy</a>\r\n");
      out.write("                </nav> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br><br><br><br>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  \r\n");
      out.write("<div id=\"loader\" class=\"loading-holder\">\r\n");
      out.write("  <img id=\"loading-image\" class=\"loading-image\" src=\"../images/modal-loader.gif\" alt=\"Loading...\" />\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"/js/login.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
