/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2024-03-07 08:09:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminconsole;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.text.DateFormat;

public final class closePin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/common.css\"/>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container container-background\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-wrap-div\" id=\"closePinListDiv\">\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t<div class=\"col-md-12\">\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t    <ol class=\"breadcrumb\">\r\n");
      out.write("\t        <li class=\"breadcrumb-item\"><b>PIN Management</b></li>\r\n");
      out.write("\t        <li class=\"breadcrumb-item active\"><b>Close PIN</b></li>\r\n");
      out.write("\t    </ol>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t\t<div class=\"col-md-6\"><p class=\"main-wrap-header\">Close PIN Details</p></div>\r\n");
      out.write("\t\t<div class=\"col-md-6 text-right\" >\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"closePinBtnId\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus-sign\"></i>\r\n");
      out.write("\t\t\t\t\t\tClose PIN\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-12 responsive-table\" id=\"pinListSearchTableDiv\">\r\n");
      out.write("\t\t\t<table id=\"pinListSearchTable\" class=\"table table-striped table-bordered table-sm\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN Number</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th>Project Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Project Sponsor Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Project Manager Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN Start Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN End Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"10%\">Action</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"main-wrap-div\" style=\"display: none;\" id=\"selectPinDivId\">\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t\t<div class=\"col-md-6\"><p class=\"main-wrap-header\">Closed PIN</p></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t<label for=\"projectType\" class=\"col-sm-2 col-form-label\">Select PIN*</label>\r\n");
      out.write("\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t <select class=\"form-control\" name=\"selectPin\" id=\"selectPinId\"></select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-sm-2\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"main-wrap-div\" style=\"display: none;\" id=\"closePinDivId\">\r\n");
      out.write("\t<!-- <div class=\"row form-group\">\r\n");
      out.write("\t\t<div class=\"col-md-6\"><p class=\"main-wrap-header\">Create PIN</p></div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"error-messages-scroll\" id=\"closePinErrorDiv\" style=\"padding: 0px 2px 10px 0px;\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form id=\"closePinFormId\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"pinHeaderId\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"pinCloserDetailsId\">\r\n");
      out.write("    <div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("      <div class=\"card\">\r\n");
      out.write("         <div class=\"card-header\" id=\"headingOne\">\r\n");
      out.write("             <h2 class=\"mb-0\">\r\n");
      out.write("                 <button type=\"button\" class=\"btn btn-link collapsed\" id=\"buttonOne\" data-toggle=\"collapse\" data-target=\"#collapseOne\"><i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Basic Pin Info</button>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("             </h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"collapseOne\" class=\"collapse\" aria-labelledby=\"headingOne\" data-parent=\"#accordionExample\">\r\n");
      out.write("         <div class=\"card-body\">        \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"projectName\" class=\"col-sm-2 col-form-label\">Project Name*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"projectNameId\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t <label for=\"projectManagerId\" class=\"col-sm-2 col-form-label\">Project Manager Name*</label>\r\n");
      out.write("\t\t\t     <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t       <select class=\"form-control\" name=\"manager\" id=\"managerId\" onchange=\"populateDeliveryOrg(this)\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- PIN Id TextBox -->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"pinNo\" class=\"col-sm-2 col-form-label\">PIN No*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"pinNoId\" name=\"pinNo\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t         <!-- <div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t    <label for=\"projectRepository\" class=\"col-sm-2 col-form-label\">Project Repository</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"projectRepositoryId\" placeholder=\"projectRepository\">\r\n");
      out.write("\t\t\t    </div> -->\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- Pin Start Date and Pin End Date-->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"pinStartDate\" class=\"col-sm-2 col-form-label\">PIN Start Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"pinStartDateId\" name=\"pinStartDate\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t  <label for=\"pinEndDate\" class=\"col-sm-2 col-form-label\">PIN End Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"pinEndDateId\" name=\"pinEndDate\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t  <!-- Revised End Date-->\r\n");
      out.write("\t         <div class=\"form-group row\" id=\"revisedEndDateDiv\">\r\n");
      out.write("\t\t\t    <label for=\"revisedEndDate\" class=\"col-sm-2 col-form-label\">Revised End Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"revisedEndDateId\" name=\"revisedEndDate\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t  <label for=\"pinCloseDate\" class=\"col-sm-2 col-form-label\">PIN Close Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"pinCloseDateId\" name=\"pinCloseDate\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"projectRepository\" class=\"col-sm-2 col-form-label\">Project Repository*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <textarea class=\"form-control\" id=\"projectRepositoryId\" maxlength=\"500\" placeholder=\"Project Repository\"></textarea>\r\n");
      out.write("\t\t\t    </div> \t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t         <!-- <div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t    <label for=\"projectRepository\" class=\"col-sm-2 col-form-label\">Project Repository</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"projectRepositoryId\" placeholder=\"projectRepository\">\r\n");
      out.write("\t\t\t    </div> -->\r\n");
      out.write("\t\t\t </div>\t \r\n");
      out.write("\t\t\r\n");
      out.write("         </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingTwo\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\" id=\"buttonTwo\" data-toggle=\"collapse\" data-target=\"#collapseTwo\">\r\n");
      out.write("                <i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Type Of Engagement</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionExample\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"coeClassification\" class=\"col-sm-2 col-form-label\">Coe Classification*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t      <select class=\"form-control\" name=\"coeClassification\" multiple id=\"coeClassificationId\">\r\n");
      out.write("\t\t\t  \t\t<option value=\"Data Analytics\">Data Analytics</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"Software Integration\">Software Integration</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"Quality Assurance\">Quality Assurance</option>\t\t\t \t\t\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"coeSubClassification\" class=\"col-sm-2 col-form-label\">Coe Sub Classification</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"coeSubClassificationId\" name=\"coeSubClassification\" maxlength=\"200\" placeholder=\"Coe Sub Classification\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"business\" class=\"col-sm-2 col-form-label\">Business*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t      <textarea class=\"form-control\" id=\"businessId\" name=\"business\" maxlength=\"1000\" placeholder=\"Business\"></textarea>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t <label for=\"solution\" class=\"col-sm-2 col-form-label\">Solution*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t       <textarea class=\"form-control\" id=\"solutionId\" name=\"solution\" maxlength=\"1000\" placeholder=\"Solution\"></textarea>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"natureOfProject\" class=\"col-sm-2 col-form-label\">Nature Of Project*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t      <select class=\"form-control\" name=\"natureOfProject\" multiple id=\"natureOfProjectId\">\r\n");
      out.write("\t\t\t  \t\t<option value=\"Green Field Product\">Green Field Product</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"Consulting\">Consulting</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"Product Enhancement\">Product Enhancement</option>\t\t\t \t\t\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t <label for=\"inputSkillDetails\" class=\"col-sm-2 col-form-label\">Skill Required*</label>\r\n");
      out.write("\t\t\t     <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t       <textarea class=\"form-control\" id=\"skillRequiredId\" name=\"skillRequired\" maxlength=\"500\" placeholder=\"Skill Required\"></textarea> \r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t  \t\t  \r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingThree\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\"  id=\"buttonThree\" data-toggle=\"collapse\" data-target=\"#collapseThree\">\r\n");
      out.write("                <i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Learnings</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseThree\" class=\"collapse\" aria-labelledby=\"headingThree\" data-parent=\"#accordionExample\">\r\n");
      out.write("          <div class=\"card-body\">        \r\n");
      out.write("          <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"technicalLearning\" class=\"col-sm-2 col-form-label\">Technical</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"technicalLearningId\" name=\"technicalLearning\" maxlength=\"1000\" placeholder=\"Technical Learning\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\t  \r\n");
      out.write("\t\t <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"peopleLearning\" class=\"col-sm-2 col-form-label\">People</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"peopleLearningId\" name=\"peopleLearning\" maxlength=\"1000\" placeholder=\"People Learning\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"processLearning\" class=\"col-sm-2 col-form-label\">Process</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"processLearningId\" name=\"processLearning\" maxlength=\"1000\" placeholder=\"Process Learning\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"effortTimeline\" class=\"col-sm-2 col-form-label\">Effort/Timeline</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"effortTimelineId\" name=\"effortTimeline\" maxlength=\"500\" placeholder=\"Effort/Timeline\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingFour\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\"  id=\"buttonFour\" data-toggle=\"collapse\" data-target=\"#collapseFour\">\r\n");
      out.write("                <i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Performance</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFour\" class=\"collapse\" aria-labelledby=\"headingFour\" data-parent=\"#accordionExample\">\r\n");
      out.write("          <div class=\"card-body\">        \r\n");
      out.write("          <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectObjPlanned\" class=\"col-sm-2 col-form-label\">Project Objectives Planned*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectObjPlannedId\" name=\"projectObjPlanned\" maxlength=\"1000\" placeholder=\"Project Objectives Planned\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\t  \r\n");
      out.write("\t\t <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectObjAchieved\" class=\"col-sm-2 col-form-label\">Project Objectives Achieved*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectObjAchievedId\" name=\"projectObjAchieved\" maxlength=\"1000\" placeholder=\"Project Objectives Achieved\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"milestonesPlanned\" class=\"col-sm-2 col-form-label\">Milestones Planned</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"milestonesPlannedId\" name=\"milestonesPlanned\" maxlength=\"1000\" placeholder=\"Milestones Planned\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"milestonesAchieved\" class=\"col-sm-2 col-form-label\">Milestones Achieved</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"milestonesAchievedId\" name=\"milestonesAchieved\" maxlength=\"1000\" placeholder=\"Milestones Achieved\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"plannedAllocation\" class=\"col-sm-2 col-form-label\">People Planned Allocation</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"plannedAllocationId\" name=\"plannedAllocation\" maxlength=\"500\" placeholder=\"People Planned Allocation\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"actualAllocation\" class=\"col-sm-2 col-form-label\">People Actual Allocation</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"actualAllocationId\" name=\"actualAllocation\" maxlength=\"500\" placeholder=\"People Actual Allocation\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"issuesIdentified\" class=\"col-sm-2 col-form-label\">Issues Identified</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"issuesIdentifiedId\" name=\"issuesIdentified\" maxlength=\"100\" placeholder=\"Issues Identified\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"issuesFixed\" class=\"col-sm-2 col-form-label\">Issues Fixed</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"issuesFixedId\" name=\"issuesFixed\" maxlength=\"100\" placeholder=\"Issues Fixed\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"issuesRepeated\" class=\"col-sm-2 col-form-label\">Issues Repeated</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"issuesRepeatedId\" name=\"issuesRepeated\" maxlength=\"100\" placeholder=\"Issues Repeated\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"riskIdentifiedMitigated\" class=\"col-sm-2 col-form-label\">Risk Identified & Mitigated</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"riskIdentifiedMitigatedId\" name=\"riskIdentifiedMitigated\" maxlength=\"1000\" placeholder=\"Risk Identified & Mitigated\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"physicalResourceRelease\" class=\"col-sm-2 col-form-label\">Hardware & Software Resources To Be Released*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"physicalResourceReleaseId\" name=\"physicalResourceRelease\" maxlength=\"100\" placeholder=\"Hardware & Software Resources To Be Released\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"form-group row\">\r\n");
      out.write("\t\t    <label for=\"revokeAllDataAccess\" class=\"col-sm-2 col-form-label\">Revoke All Data Access:</label>\r\n");
      out.write("\t\t    <div class=\"col-sm-8 text-align-left\">\r\n");
      out.write("\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"YES\" name=\"revokeAllDataAccess\" onclick=\"enableRasonDiv('YES')\">&nbsp;&nbsp;&nbsp;&nbsp;Yes</label>\r\n");
      out.write("\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" value=\"NO\" name=\"revokeAllDataAccess\" onclick=\"enableRasonDiv('NO')\">&nbsp;&nbsp;&nbsp;&nbsp;No</label> \r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t  </div> \r\n");
      out.write("\t\t   <div class=\"form-group row\" id=\"reasonDivId\">\r\n");
      out.write("\t\t\t<label for=\"reason\" class=\"col-sm-2 col-form-label\">Reason*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"revokeAccessReasonId\" name=\"revokeAccessReason\" maxlength=\"500\" placeholder=\"Reason\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingFive\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\"  id=\"buttonFive\" data-toggle=\"collapse\" data-target=\"#collapseFive\">\r\n");
      out.write("                <i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Comment</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFive\" class=\"collapse\" aria-labelledby=\"headingFive\" data-parent=\"#accordionExample\">\r\n");
      out.write("         <div class=\"card-body\">\r\n");
      out.write("         <!-- Pin Submitted Comments TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("         <table class=\"table table-bordered\" id=\"commentTable\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <th>Comment</th>\r\n");
      out.write("                   <th>Commented By</th>\r\n");
      out.write("                   <th>Commented On</th>\t\t\t                        \r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody></tbody>\r\n");
      out.write("\t\t</table>       \r\n");
      out.write("         </div>       \r\n");
      out.write("         <!-- Pin Comments TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"pinComments\" class=\"col-sm-2 col-form-label\">Comments*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"pinCommentsId\" name=\"pinComments\" maxlength=\"1000\" placeholder=\"Comments\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\t\t  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"submitButtonDiv\">\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"createClosePinBtnId\" onclick=\"createClosePIN()\" style=\"display: none;\">Submit</button>\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"updateClosePinBtnId\" onclick=\"updateClosePIN()\" style=\"display: none;\">Update</button>\r\n");
      out.write("    \t<button type=\"button\" class=\"btn btn-secondary\" onclick=\"backToClosePinList()\">Cancel</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"approveRejectButtonDiv\" style=\"display: none;\">\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" onclick=\"approveClosePIN()\">Approved</button>\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" onclick=\"rejectClosePIN()\">Reject</button>\r\n");
      out.write("    \t<button type=\"button\" class=\"btn btn-secondary\" onclick=\"backToClosePinList()\">Cancel</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"loader\" class=\"loading-holder\">\r\n");
      out.write("  <img id=\"loading-image\" class=\"loading-image\" src=\"images/modal-loader.gif\" alt=\"Loading...\" />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"./js/closePin.js\"></script>\r\n");
      out.write("<script src=\"./js/pinCRCommon.js\"></script>\r\n");
      out.write("<script src=\"./js/utility.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
