/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2024-03-07 11:35:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminconsole;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class headerMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String role = session.getAttribute("role").toString();

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/headerMenu.css\"/>\t\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("\t    <div class=\"container-fluid\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a class=\"navbar-brand\">\r\n");
      out.write("\t\t\t<img src=\"images/app_logo.png\" alt=\"\" style=\"position:relative;max-height: 58px;\">\r\n");
      out.write("\t\t</a> \r\n");
      out.write("\t    \r\n");
      out.write("\t      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t        <span class=\"fa fa-bars\"></span> Menu\r\n");
      out.write("\t      </button>\r\n");
      out.write("\t      <!-- <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t        <ul class=\"navbar-nav m-auto\">\r\n");
      out.write("\t        \t<li class=\"nav-item active\"><a href=\"#\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("\t        \t<li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Page</a>\r\n");
      out.write("              <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("              \t<a class=\"dropdown-item\" href=\"#\">Page 1</a>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"#\">Page 2</a>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"#\">Page 3</a>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"#\">Page 4</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"?target=resourceMaster\" class=\"nav-link\">Resource</a></li>       \t\r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"?target=pinAllocation\" class=\"nav-link\">Pin Management</a></li>\r\n");
      out.write("\t          <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">Contact</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t      </div> -->\r\n");
      out.write("\t      <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t        <ul class=\"navbar-nav m-auto\">\t        \r\n");
      out.write("\t\t        <li class=\"nav-item dropdown\">\r\n");
      out.write("\t              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Master Screen</a>\r\n");
      out.write("\t              <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("\t              \t<a href=\"?target=customerMaster\" class=\"dropdown-item\">Customer</a>\r\n");
      out.write("\t                <a href=\"?target=sourceMaster\" class=\"dropdown-item\">Source</a>\r\n");
      out.write("\t                <a href=\"?target=resourceMaster\" class=\"dropdown-item\">Resource</a>\r\n");
      out.write("\t                <a href=\"?target=vendorMaster\" class=\"dropdown-item\">Vendor</a>\r\n");
      out.write("\t                <a href=\"?target=designationMaster\" class=\"dropdown-item\">Designation</a>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </li> \t\r\n");
      out.write("\t        \t<!-- <li class=\"nav-item\"><a href=\"?target=pinAllocation\" class=\"nav-link\">PIN Management</a></li> -->\r\n");
      out.write("\t        \t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">PIN Management</a>\r\n");
      out.write("\t             <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("\t              \t<a href=\"?target=pinAllocation\" class=\"dropdown-item\">Create/ View PIN</a>\t              \t\r\n");
      out.write("\t\t\t\t  \t<a href=\"?target=closePin\" class=\"dropdown-item\">Close PIN</a>\t\t\t\t  \r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </li> \r\n");
      out.write("\t        \t<li class=\"nav-item\"><a href=\"?target=changeRequest\" class=\"nav-link\">Change Request</a></li>\r\n");
      out.write("\t        \t");
	
				if(role !=null && (role.equalsIgnoreCase("DH") || role.equalsIgnoreCase("HR") || role.equalsIgnoreCase("PMO") || role.equalsIgnoreCase("Finance"))) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <li class=\"nav-item\"><a href=\"?target=resourceAllocationReport\" class=\"nav-link\">Resource Allocation Report</a></li> -->\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Report</a>\r\n");
      out.write("\t             <div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("\t              \t<a href=\"?target=resourceListReport\" class=\"dropdown-item\">Resource List Report</a>\r\n");
      out.write("\t              \t<a href=\"?target=resourceAllocationReport\" class=\"dropdown-item\">Resource Allocation Report</a>\r\n");
      out.write("\t              \t");
	
					if(role.equalsIgnoreCase("DH")) {
				   
      out.write("\t\t  \t\r\n");
      out.write("\t\t\t\t  \t<a href=\"?target=billableReport\" class=\"dropdown-item\">Billable Report</a>\r\n");
      out.write("\t\t\t\t   ");

					}
				   
      out.write("\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t            </li> \r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\" style=\" margin-right: 75px;\"> \r\n");
      out.write("\t\t\t\t<!-- <li>\r\n");
      out.write("\t\t\t\t\t<a href=\"../logout.jsp\"><i class=\"fa fa-sign-out\" title=\"Logout\" style=\"font-size: 25px;color: white;cursor: pointer;\"></i></a>\r\n");
      out.write("\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("              \t \t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown04\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("              \t \t\t<i class=\"fa fa-user\" title=\"Logout\" style=\"font-size: 25px;color: white;cursor: pointer;\"></i>\r\n");
      out.write("              \t \t</a>\r\n");
      out.write("             \t \t<div class=\"dropdown-menu\" aria-labelledby=\"dropdown04\">\r\n");
      out.write("              \t\t\t<!-- <a class=\"dropdown-item\" href=\"?target=resetPassword\" >Reset Password</a> -->\r\n");
      out.write("               \t \t\t<a class=\"dropdown-item\" href=\"../logout.jsp\">Logout</a>\r\n");
      out.write("              \t</div>\r\n");
      out.write("            \t</li>\r\n");
      out.write("    \t\t</ul>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("<script src=\"./js/headerMenu.js\"></script>\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
