/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2024-02-25 17:19:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.adminconsole;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.text.DateFormat;

public final class pinAllocation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/common.css\"/>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- <nav>\r\n");
      out.write("    <ol class=\"breadcrumb\">\r\n");
      out.write("        <li class=\"breadcrumb-item\"><a href=\"?target=customerMaster\">Home</a></li>\r\n");
      out.write("        <li class=\"breadcrumb-item active\"><b>Resource Master</b></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("</nav> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container container-background\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-wrap-div\" id=\"pinListDiv\">\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t<div class=\"col-md-12\">\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t    <ol class=\"breadcrumb\">\r\n");
      out.write("\t        <li class=\"breadcrumb-item\"><b>PIN Management</b></li>\r\n");
      out.write("\t        <li class=\"breadcrumb-item active\"><b>Create/ View PIN</b></li>\r\n");
      out.write("\t    </ol>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t\t<div class=\"col-md-6\"><p class=\"main-wrap-header\">PIN Details</p></div>\r\n");
      out.write("\t\t<div class=\"col-md-6 text-right\" >\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"addPineBtnId\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-plus-sign\"></i>\r\n");
      out.write("\t\t\t\t\t\tAdd PIN\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-12 responsive-table\" id=\"pinListSearchTableDiv\">\r\n");
      out.write("\t\t\t<table id=\"pinListSearchTable\" class=\"table table-striped table-bordered table-sm\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN Number</th>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th>Project Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Project Sponsor Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Project Manager Name</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Contract Value</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN Start Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>PIN End Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Revised End Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Project Hold Date</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"10%\">Action</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"main-wrap-div\" style=\"display: none;\" id=\"createNewPinDivId\">\r\n");
      out.write("\t<div class=\"row form-group\">\r\n");
      out.write("\t\t<div class=\"col-md-6\"><p class=\"main-wrap-header\">Create PIN</p></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"error-messages-scroll\" id=\"addPinErrorDiv\" style=\"padding: 0px 2px 10px 0px;\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form id=\"createPinFormId\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"pinHeaderId\">\r\n");
      out.write("    <div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("      <div class=\"card\">\r\n");
      out.write("         <div class=\"card-header\" id=\"headingOne\">\r\n");
      out.write("             <h2 class=\"mb-0\">\r\n");
      out.write("                 <button type=\"button\" class=\"btn btn-link collapsed\" id=\"buttonOne\" data-toggle=\"collapse\" data-target=\"#collapseOne\"><i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Basic Pin Info</button>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("             </h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"collapseOne\" class=\"collapse\" aria-labelledby=\"headingOne\" data-parent=\"#accordionExample\">\r\n");
      out.write("         <div class=\"card-body\">\r\n");
      out.write("        \r\n");
      out.write("         \t <!-- Project Type Dropdown and Project Category Dropdown-->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"projectType\" class=\"col-sm-2 col-form-label\">Project Type*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t      <select class=\"form-control\" name=\"projectType\" id=\"projectTypeId\">\r\n");
      out.write("\t\t\t  \t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t  \t\t<option value=\"I\">Internal</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"R\">Revenue</option>\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t <label for=\"projectCategory\" class=\"col-sm-2 col-form-label\">Project Category*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t       <select class=\"form-control\" name=\"projectCategory\" id=\"projectCategoryId\">\r\n");
      out.write("\t\t\t  \t\t<option value=\"\">Select</option>\r\n");
      out.write("\t\t\t  \t\t<option value=\"S\">Software Engineering</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"A\">Analytics</option>\r\n");
      out.write("\t\t\t \t\t<option value=\"P\">Process</option>\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- customer Dropdown and projectName textbox-->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"customer\" class=\"col-sm-2 col-form-label\">Customer*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t      <select class=\"form-control\" name=\"customer\" id=\"customerId\">\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t <label for=\"projectName\" class=\"col-sm-2 col-form-label\">Project Name*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t        <input type=\"text\" class=\"form-control\" id=\"projectNameId\" maxlength=\"45\" placeholder=\"Project Name\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- Project Sponsor Name textbox and Project Manager Name Drpdown-->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"sponsorName\" class=\"col-sm-2 col-form-label\">Project Sponsor Name*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"sponsorNameId\" maxlength=\"100\" placeholder=\"Project Sponsor Name\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t <label for=\"projectManagerId\" class=\"col-sm-2 col-form-label\">Project Manager Name*</label>\r\n");
      out.write("\t\t\t     <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t       <select class=\"form-control\" name=\"manager\" id=\"managerId\" onchange=\"populateDeliveryOrg(this)\">\r\n");
      out.write("\t\t\t\t  </select>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- Contract Value TextBox -->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"contractValue\" class=\"col-sm-2 col-form-label\">Contract Value*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"contractValueId\" name=\"contractValue\" maxlength=\"9\"  onkeypress=\"return validateFloatKeyPress(this,event,6);\" placeholder=\"Contract Value\">\r\n");
      out.write("\t\t\t    </div>\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- Source Name TextBox -->\r\n");
      out.write("\t         <div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t    <label for=\"deliveryOrg\" class=\"col-sm-2 col-form-label\">Delivery Organization</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"text\" class=\"form-control\" id=\"deliveryOrgId\" placeholder=\"Delivery Organization\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <!-- Pin Start Date and Pin End Date-->\r\n");
      out.write("\t         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t    <label for=\"pinStartDate\" class=\"col-sm-2 col-form-label\">PIN Start Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"pinStartDateId\" name=\"pinStartDate\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<div class=\"col-sm-1\"></div>\r\n");
      out.write("\t\t\t\t  <label for=\"pinEndDate\" class=\"col-sm-2 col-form-label\">PIN End Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"pinEndDateId\" name=\"pinEndDate\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t  <!-- Revised End Date-->\r\n");
      out.write("\t         <div class=\"form-group row\" id=\"revisedEndDateDiv\" style=\"display: none;\">\r\n");
      out.write("\t\t\t    <label for=\"revisedEndDate\" class=\"col-sm-2 col-form-label\">Revised End Date*</label>\r\n");
      out.write("\t\t\t    <div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t  <input type=\"date\" class=\"form-control\" id=\"revisedEndDateId\" name=\"revisedEndDate\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t </div>\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("         </div>\r\n");
      out.write("         </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingTwo\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\" id=\"buttonTwo\" data-toggle=\"collapse\" data-target=\"#collapseTwo\"><i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Project Details</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionExample\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("        \r\n");
      out.write("         <!-- Project Objectives TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectObjectives\" class=\"col-sm-2 col-form-label\">Project Objectives</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectObjectivesId\" name=\"projectObjectives\" maxlength=\"500\" placeholder=\"Project Objectives\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Deliverables TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectDeliverables\" class=\"col-sm-2 col-form-label\">Project Deliverables</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectDeliverablesId\" name=\"projectDeliverables\" maxlength=\"2000\" placeholder=\"Project Deliverables\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <!-- Project In Scope TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectInScope\" class=\"col-sm-2 col-form-label\">Project In Scope</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectInScopeId\" name=\"projectInScope\" maxlength=\"2000\"\t placeholder=\"Project In Scope\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Out of Scope TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectOutScope\" class=\"col-sm-2 col-form-label\">Project Out Of Scope</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectOutScopeId\" name=\"projectOutScope\" maxlength=\"2000\" placeholder=\"Project Out Of Scope\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Assumptions TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectAssumptions\" class=\"col-sm-2 col-form-label\">Project Assumptions</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectAssumptionsId\" name=\"projectAssumptions\" maxlength=\"1000\" placeholder=\"Project Assumptions\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Constraints TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectConstraints\" class=\"col-sm-2 col-form-label\">Project Constraints</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectConstraintsId\" name=\"projectConstraints\" maxlength=\"1000\" placeholder=\"Project Constraints\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Initial Risks Mitigation TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectInitialRisks\" class=\"col-sm-2 col-form-label\">Project Initial Risks Mitigation</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectInitialRisksId\" name=\"projectInitialRisks\" maxlength=\"2000\" placeholder=\"Project Initial Risks Mitigation\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!-- Project Key Milestones TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"projectKeyMilestones\" class=\"col-sm-2 col-form-label\">Project Key Milestones</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"projectKeyMilestonesId\" name=\"projectKeyMilestones\" maxlength=\"1000\" placeholder=\"Project Key Milestones\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \t\t  \r\n");
      out.write("        </div>\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header\" id=\"headingThree\">\r\n");
      out.write("            <h2 class=\"mb-0\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-link collapsed\"  id=\"buttonThree\" data-toggle=\"collapse\" data-target=\"#collapseThree\"><i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp;Comment</button>\r\n");
      out.write("            </h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseThree\" class=\"collapse\" aria-labelledby=\"headingThree\" data-parent=\"#accordionExample\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("  \r\n");
      out.write("         <!-- Pin Submitted Comments TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("         <table class=\"table table-bordered\" id=\"commentTable\">\r\n");
      out.write("            <thead>\r\n");
      out.write("               <tr>\r\n");
      out.write("                   <th>Comment</th>\r\n");
      out.write("                   <th>Commented By</th>\r\n");
      out.write("                   <th>Commented On</th>\t\t\t                        \r\n");
      out.write("               </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody></tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("         \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <!-- Pin Comments TextArea -->\r\n");
      out.write("         <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"pinComments\" class=\"col-sm-2 col-form-label\">Comments*</label>\r\n");
      out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t<textarea class=\"form-control\" id=\"pinCommentsId\" name=\"pinComments\" maxlength=\"1000\" placeholder=\"Comments\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card\">\r\n");
      out.write("         <div class=\"card-header\" id=\"headingFour\">\r\n");
      out.write("             <h2 class=\"mb-0\">\r\n");
      out.write("                 <button type=\"button\" class=\"btn btn-link collapsed\" id=\"buttonFour\" data-toggle=\"collapse\" data-target=\"#collapseFour\"><i class=\"fa fa-plus-circle\"></i>&nbsp;&nbsp; Resource Details</button>                     \r\n");
      out.write("             </h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"collapseFour\" class=\"collapse\" aria-labelledby=\"headingFour\" data-parent=\"#accordionExample\">\r\n");
      out.write("             <div class=\"card-body\">\r\n");
      out.write("             \r\n");
      out.write("             \t<!-- Add Human Resource -->\r\n");
      out.write("                <div class=\"container-lg\">\r\n");
      out.write("\t\t\t    <div class=\"table-wrapper-responsive\">\r\n");
      out.write("\t\t\t        <div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t            <div class=\"table-title\">\r\n");
      out.write("\t\t\t                <div class=\"row\">\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-8\"><h2>Human Resource</h2></div>\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t                        <!-- <button type=\"button\" class=\"btn btn-info add-new add-new-HR\" id=\"addHumanResourceBtn\"><i class=\"fa fa-plus\"></i> Add New</button> -->\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div class=\"error-messages-scroll\" id=\"humanResourceErrorDiv\" style=\"padding: .5rem 1rem;\"></div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <table class=\"table table-bordered\" id=\"humanResourceTable\">\r\n");
      out.write("\t\t\t                <thead>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                        <th>Resource Name</th>\r\n");
      out.write("\t\t\t                        <th>Employee Id</th>\r\n");
      out.write("\t\t\t                        <th>Role</th>\r\n");
      out.write("\t\t\t                        <th>Allocation(in %)</th>\r\n");
      out.write("\t\t\t                        <th>Start Date</th>\r\n");
      out.write("\t\t\t                        <th>End Date</th>\r\n");
      out.write("\t\t\t                        <th>Actions</th>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                </thead>\r\n");
      out.write("\t\t\t                <tbody></tbody>\r\n");
      out.write("\t\t\t            </table>\r\n");
      out.write("\t\t\t            <div class=\"table-title\">\r\n");
      out.write("\t\t\t                <div class=\"row\">\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-8\"></div>\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t                        <button type=\"button\" class=\"btn btn-info add-new add-new-HR\" id=\"addHumanResourceBtn\"><i class=\"fa fa-plus\"></i> Add New</button>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t        \t</div>\r\n");
      out.write("\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Add Physical Resource -->\r\n");
      out.write("\t\t\t\t<div class=\"container-lg\">\r\n");
      out.write("\t\t\t    <div class=\"table-wrapper-responsive\">\r\n");
      out.write("\t\t\t        <div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t            <div class=\"table-title\">\r\n");
      out.write("\t\t\t                <div class=\"row\">\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-8\"><h2>Physical Resource</h2></div>\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t                        <!-- <button type=\"button\" class=\"btn btn-info add-new add-new-PR\" id=\"addPhysicalResourceBtn\"><i class=\"fa fa-plus\"></i> Add New</button> -->\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                    <div class=\"error-messages-scroll\" id=\"physicalResourceErrorDiv\" style=\"padding: .5rem 1rem;\"></div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <table class=\"table table-bordered\" id=\"physicalResourceTable\">\r\n");
      out.write("\t\t\t                <thead>\r\n");
      out.write("\t\t\t                    <tr>\r\n");
      out.write("\t\t\t                        <th>Description</th>\r\n");
      out.write("\t\t\t                        <th>Allocation(in %)</th>\r\n");
      out.write("\t\t\t                        <th>Start Date</th>\r\n");
      out.write("\t\t\t                        <th>End Date</th>\r\n");
      out.write("\t\t\t                        <th>Actions</th>\r\n");
      out.write("\t\t\t                    </tr>\r\n");
      out.write("\t\t\t                </thead>\r\n");
      out.write("\t\t\t                <tbody></tbody>\r\n");
      out.write("\t\t\t            </table>\r\n");
      out.write("\t\t\t            <div class=\"table-title\">\r\n");
      out.write("\t\t\t                <div class=\"row\">\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-8\"></div>\r\n");
      out.write("\t\t\t                    <div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t                        <button type=\"button\" class=\"btn btn-info add-new add-new-PR\" id=\"addPhysicalResourceBtn\"><i class=\"fa fa-plus\"></i> Add New</button>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t        \t</div>\r\n");
      out.write("\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"submmitButtonDiv\">\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"savePinBtnId\" onclick=\"savePinAllocation()\" style=\"display: none;\">Submit</button>\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"updatePinBtnId\" onclick=\"updatePinAllocation()\" style=\"display: none;\">Update</button>\r\n");
      out.write("    \t<button type=\"button\" class=\"btn btn-secondary\" onclick=\"backToPinList()\">Cancel</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"approveRejectButtonDiv\" style=\"display: none;\">\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"savePinBtnId\" onclick=\"approvePin()\">Approved</button>\r\n");
      out.write("    \t<button type=\"submit\" class=\"btn btn-primary\" id=\"savePinBtnId\" onclick=\"rejectPin()\">Reject</button>\r\n");
      out.write("    \t<button type=\"button\" class=\"btn btn-secondary\" onclick=\"backToPinList()\">Cancel</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"loader\" class=\"loading-holder\">\r\n");
      out.write("  <img id=\"loading-image\" class=\"loading-image\" src=\"images/modal-loader.gif\" alt=\"Loading...\" />\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"./js/pinAllocation.js\"></script>\r\n");
      out.write("<script src=\"./js/pinCRCommon.js\"></script>\r\n");
      out.write("<script src=\"./js/utility.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
